name: Deploy to GCP
on:
    push:

env:
    GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
    TF_STATE_BUCKET_NAME: ${{ secrets.GCP_TF_STATE_BUCKET }}

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v3
            - id: auth 
              name: Authenticate to GCP
              uses: google-github-actions/auth@v1
              with:
                token_format: access_token
                workload_identity_provider: projects/621518571741/locations/global/workloadIdentityPools/my-pool-123/providers/my-oidc-provider
                service_account: github@evident-pipe-284110.iam.gserviceaccount.com


